# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "84e3f256544134606ade642d264d4eb8"
name = "Order Editing"
handle = "order-editing-7"
application_url = "https://outdoors-patrol-nor-sponsors.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://outdoors-patrol-nor-sponsors.trycloudflare.com/auth/callback",
  "https://outdoors-patrol-nor-sponsors.trycloudflare.com/auth/shopify/callback",
  "https://outdoors-patrol-nor-sponsors.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
